#controllers:
    #resource: #../src/
       # path: ../../src/Controller/
        #namespace: Api\Controller
        #namespace: App\Controller\Api
   # type: attribute

controllers:
    resource: ../src/Controller/
    type: attribute